<?php
/**
 * Copyright by Oleg Dudkin.
 * Project: CMS "DON e-Commerce"
 * File name: en.php
 * Date: 3/5/2017
 * Time: 6:42 PM
 * Return language array
 */
return array(
    #language
    'lang' => 'en',
    'en' => 'english',
    'ru' => 'русский',
    #main
    'sign_in' => 'sign in',
    'sign_up' => 'sign up',
    'language' => 'language',
    'profile' => 'Profile',
    'logout' => 'Logout',
    'cart' => 'Cart',
    'home' => 'Home',
    'shop' => 'Shop',
    'catalog' => 'Catalog',
    'blog' => 'Blog',
    'about_us' => 'About us',
    'contacts' => 'Contacts',
    'categories' => 'Categories',
    'send' => 'send',
    'add' => 'add',
    'read' => 'Read...',
    'author' => 'author',
    'articles' => 'Articles',
    'create' => 'create',
    'admin_panel' => 'Admin panel',
    'title' => 'Title',
    'description' => 'Description',
    'full_text' => 'Full text',
    'items_code' => 'items&nbsp;code',
    'price' => 'price',
    'amount' => 'amount',
    'total' => 'total',
    'checkout' => 'checkout',
    'delete' => 'delete',
    'country' => 'country',
    'state' => 'state',
    'city' => 'city',
    'street' => 'street',
    'email' => 'E-mail',
    'password' => 'Password',
    'orders' => 'orders',
    'personal_sales' => 'personal sales',
    'reports' => 'reports',
    'hello' => 'Hello',
    'status' => 'Status',
    'edit' => 'edit',
    'none' => 'none',
    'save' => 'save',
    #Phrases
    'last_products' => 'last products',
    'recommend' => 'recommend',
    'text_us' => 'Text us',
    'full_name' => 'Full name',
    'subject' => 'Subject',
    'message' => 'Message',
    'last_articles' => 'Last articles',
    'back_to_blog' => 'Back to blog',
    'categories_empty' => 'The list of categories is empty',
    'сhoose_photo' => 'Choose photo',
    'items_cart' => 'Items in the cart',
    'cart_empty' => 'Cart is empty',
    'selected_products' => 'Selected products',
    'phone_number' => 'Phone number',
    'house_number' => 'House number',
    'apartment_number' => 'Apartment number',
    'сomment_order' => 'Comment to order',
    'your_message' => 'Your message',
    'user_profile' => 'User\'s profile',
    'create_account' => 'Create an account',
    'zip_code' => 'Your zip code',
    'edit_address' => 'Edit the bring address',
    'bring_address' => 'The bring address',
    'main_data' => 'The main data',
    #errors
    'error_create_folder' => 'Error create the folder.',
    'too_big_img_size' => 'This image is too big, '.MAX_SIZE_IMG.'Mb. maximum.',
    'error_upload_file' => 'Error uploading the file.',
    'error_phone_number' => 'Wrong phone number format.',
    'error_title_country' => 'Wrong the title of country.',
    'error_title_state' => 'Wrong the title of state.',
    'error_title_city' => 'Wrong the title of city.',
    'error_title_street' => 'Wrong the title of street.',
    'error_number_house' => 'The number of house too long.',
    'error_number_apartment' => 'The number of apartment too long.',
    'error_zip_code_long' => 'The zip code too long.',
    'error_zip_code_short' => 'The zip code too short.',
    #large messages
    'no_products' => 'You don\'t have any products',
    'no_categories' => 'You don\'t have categories',
    'manager_contact_you' => 'To place an order fill out the form. Our manager will contact you.',
    'about_us_text' => 'This site does not sell products, and is used to demonstrate the work of CMS. For communication use the feedback form.',
);