<?php
/**
 * Copyright by Oleg Dudkin.
 * Project: CMS "DON e-Commerce"
 * File name: ru.php
 * Date: 3/5/2017
 * Time: 6:38 PM
 */
# TODO: Return language array
return array(
    #language
    'lang' => 'ru',
    'en' => 'english',
    'ru' => 'русский',
    #main
    'sign_in' => 'войти',
    'sign_up' => 'зарегистрироваться',
    'language' => 'язык',
    'profile' => 'Профиль',
    'logout' => 'Выход',
    'cart' => 'Корзина',
    'home' => 'Главная',
    'shop' => 'Магазин',
    'catalog' => 'Каталог',
    'blog' => 'Блог',
    'about_us' => 'О нас',
    'contacts' => 'Контакты',
    'categories' => 'Категории',
    'send' => 'отправить',
    'add' => 'в корзину',
    'read' => 'Читать...',
    'author' => 'автор',
    'articles' => 'Статьи',
    'create' => 'создать',
    'admin_panel' => 'Админ панель',
    'title' => 'Название',
    'description' => 'Описание',
    'full_text' => 'Полный текст',
    'items_code' => 'код&nbsp;товара',
    'price' => 'цена',
    'amount' => 'количество',
    'total' => 'итого',
    'checkout' => 'заказ',
    'delete' => 'удалить',
    'country' => 'страна',
    'state' => 'область',
    'city' => 'город',
    'street' => 'улица',
    'email' => 'Электронная почта',
    'password' => 'Пароль',
    'orders' => 'заказы',
    'personal_sales' => 'персональные скидки',
    'reports' => 'заявки',
    'hello' => 'Здравствуйте',
    'status' => 'Статус',
    'edit' => 'изменить',
    'none' => 'отсутствует',
    'save' => 'сохранить',
    #Phrases
    'last_products' => 'последние товары',
    'recommend' => 'Рекомендуем',
    'text_us' => 'Напишите нам',
    'full_name' => 'Полное имя',
    'subject' => 'Тема сообщения',
    'message' => 'Текст сообщения',
    'last_articles' => 'Последние статьи',
    'back_to_blog' => 'Вернуться',
    'categories_empty' => 'Список категорий пуст',
    'сhoose_photo' => 'Выбрать фото',
    'items_cart' => 'Товаров в корзине',
    'cart_empty' => 'Корзина пуста',
    'selected_products' => 'Выбранно товаров',
    'phone_number' => 'Номер телефона',
    'house_number' => 'Номер дома',
    'apartment_number' => 'Номер квартиры',
    'сomment_order' => 'Комментарий к заказу',
    'your_message' => 'Ваше сообщение',
    'user_profile' => 'Профиль пользователя',
    'create_account' => 'Создать аккаунт',
    'zip_code' => 'Почтовый индекс',
    'edit_address' => 'Редактировать адрес доставки',
    'bring_address' => 'Адрес доставки',
    'main_data' => 'Основные данные',
    #errors
    'error_create_folder' => 'Ошибка создания папки.',
    'too_big_img_size' => 'Слишком большое изображания, '.MAX_SIZE_IMG.'Мб максимум.',
    'error_upload_file' => 'Ошибка загрузки файла.',
    'error_phone_number' => 'Неверный формат номера телефона.',
    'error_title_country' => 'Некорректное название страны.',
    'error_title_state' => 'Некорректное название области.',
    'error_title_city' => 'Некорректное название города.',
    'error_title_street' => 'Некорректное название улицы.',
    'error_number_house' => 'Номер дома слишком длинный.',
    'error_number_apartment' => 'Номер квартиры слишком длинный.',
    'error_zip_code_long' => 'Почтовый индекс слишком длинный.',
    'error_zip_code_short' => 'Почтовый индекс слишком короткий.',
    #large messages
    'no_products' => 'У вас нет товаров',
    'no_categories' => 'У вас нет категорий',
    'manager_contact_you' => 'Чтобы сделать заказ, заполните форму. Наш менеджер свяжется с Вами.',
    'about_us_text' => 'Данный сайт не продает продукцию, и используется для демонстрации работы CMS. Для связи пользуйтесь формой обратной связи.',
);